const bedManagementData = [
  {
    bedNo: "B101",
    type: "Bed 1",
    rate: 1000,
    status: "Vacant",
    roomCategory: "Normal",
    bedType: "Bed Electronic",
    wardType: "IPD Ward 1",
    assignedPatient: null,
  },
  {
    bedNo: "B102",
    type: "Bed 2",
    rate: 2000,
    status: "Admitted",
    roomCategory: "Isolation",
    bedType: "Resuscitation Bed",
    wardType: "ICU",
    assignedPatient: "John Doe",
  },
  {
    bedNo: "B103",
    type: "Bed 3",
    rate: 1500,
    status: "Pre Discharge",
    roomCategory: "Intensive care",
    bedType: "Neonatal Warmer Bed",
    wardType: "NICU",
    assignedPatient: "Jane Smith",
  },
  {
    bedNo: "B104",
    type: "Bed 4",
    rate: 1200,
    status: "Patient Reservation",
    roomCategory: "Normal",
    bedType: "Bed Bassinet",
    wardType: "LDR",
    reservedBy: "David Johnson",
  },
  {
    bedNo: "B105",
    type: "Bed 5",
    rate: 800,
    status: "Blocked",
    roomCategory: "Isolation",
    bedType: "Bed Incubator",
    wardType: "NICU",
    assignedPatient: null,
    maintenanceReason: "Cleaning in progress",
  },
  {
    bedNo: "B106",
    type: "Bed 6",
    rate: 1100,
    status: "Vacant",
    roomCategory: "Intensive care",
    bedType: "Bed Stretcher",
    wardType: "Ventilator",
    assignedPatient: null,
  },
  {
    bedNo: "B107",
    type: "Bed 7",
    rate: 3000,
    status: "Admitted",
    roomCategory: "Normal",
    bedType: "Operating Table",
    wardType: "Operation Theater",
    assignedPatient: "Emily Davis",
  },
  {
    bedNo: "B108",
    type: "Bed 8",
    rate: 2500,
    status: "Pre Discharge",
    roomCategory: "Isolation",
    bedType: "Neonatal Warmer Bed",
    wardType: "NICU",
    assignedPatient: "Michael Brown",
  },
  {
    bedNo: "B109",
    type: "Bed 9",
    rate: 1000,
    status: "Patient Reservation",
    roomCategory: "Normal",
    bedType: "Bed Bassinet",
    wardType: "IPD Ward 2",
    reservedBy: "Sophia Wilson",
  },
  {
    bedNo: "B110",
    type: "Bed 10",
    rate: 500,
    status: "Blocked",
    roomCategory: "Intensive care",
    bedType: "Bed Electronic",
    wardType: "OT Recovery",
    assignedPatient: null,
    maintenanceReason: "Technical repair",
  },
  {
    bedNo: "B111",
    type: "Bed 11",
    rate: 1400,
    status: "Vacant",
    roomCategory: "Normal",
    bedType: "Bed Stretcher",
    wardType: "ER",
    assignedPatient: null,
  },
  {
    bedNo: "B112",
    type: "Bed 12",
    rate: 2500,
    status: "Admitted",
    roomCategory: "Isolation",
    bedType: "Resuscitation Bed",
    wardType: "ICU",
    assignedPatient: "Anna White",
  },
  {
    bedNo: "B113",
    type: "Bed 13",
    rate: 1800,
    status: "Vacant",
    roomCategory: "Normal",
    bedType: "Operating Table",
    wardType: "Operation Theater",
    assignedPatient: null,
  },
  {
    bedNo: "B114",
    type: "Bed 14",
    rate: 1000,
    status: "Patient Reservation",
    roomCategory: "Intensive care",
    bedType: "Neonatal Warmer Bed",
    wardType: "NICU",
    reservedBy: "Chris Evans",
  },
  {
    bedNo: "B115",
    type: "Bed 15",
    rate: 2200,
    status: "Admitted",
    roomCategory: "Normal",
    bedType: "Resuscitation Bed",
    wardType: "LDR",
    assignedPatient: "Daniel Craig",
  },
  {
    bedNo: "B116",
    type: "Bed 16",
    rate: 1700,
    status: "Blocked",
    roomCategory: "Isolation",
    bedType: "Bed Bassinet",
    wardType: "NICU",
    maintenanceReason: "Renovation ongoing",
  },
  {
    bedNo: "B117",
    type: "Bed 17",
    rate: 1300,
    status: "Vacant",
    roomCategory: "Normal",
    bedType: "Bed Incubator",
    wardType: "Ventilator",
    assignedPatient: null,
  },
  {
    bedNo: "B118",
    type: "Bed 18",
    rate: 900,
    status: "Blocked",
    roomCategory: "Normal",
    bedType: "Bed Stretcher",
    wardType: "OT Recovery",
    maintenanceReason: "Electrical maintenance",
  },
  {
    bedNo: "B119",
    type: "Bed 19",
    rate: 1600,
    status: "Admitted",
    roomCategory: "Intensive care",
    bedType: "Operating Table",
    wardType: "Operation Theater",
    assignedPatient: "Lily Adams",
  },
  {
    bedNo: "B120",
    type: "Bed 20",
    rate: 1250,
    status: "Pre Discharge",
    roomCategory: "Isolation",
    bedType: "Bed Electronic",
    wardType: "NICU",
    assignedPatient: "Jack Wilson",
  },
  {
    bedNo: "B121",
    type: "Bed 21",
    rate: 1500,
    status: "Vacant",
    roomCategory: "Normal",
    bedType: "Bed Incubator",
    wardType: "IPD Ward 2",
    assignedPatient: null,
  },
  {
    bedNo: "B122",
    type: "Bed 22",
    rate: 1400,
    status: "Patient Reservation",
    roomCategory: "Intensive care",
    bedType: "Bed Bassinet",
    wardType: "LDR",
    reservedBy: "Grace Taylor",
  },
  {
    bedNo: "B123",
    type: "Bed 23",
    rate: 1900,
    status: "Admitted",
    roomCategory: "Normal",
    bedType: "Neonatal Warmer Bed",
    wardType: "Ventilator",
    assignedPatient: "Ethan Carter",
  },
  {
    bedNo: "B124",
    type: "Bed 24",
    rate: 1200,
    status: "Vacant",
    roomCategory: "Isolation",
    bedType: "Operating Table",
    wardType: "ICU",
    assignedPatient: null,
  },
  {
    bedNo: "B125",
    type: "Bed 25",
    rate: 900,
    status: "Blocked",
    roomCategory: "Intensive care",
    bedType: "Resuscitation Bed",
    wardType: "NICU",
    maintenanceReason: "Deep cleaning required",
  },
];
export default bedManagementData;
